# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yeast Population Reference Panel (YPRP)
description: > # this means to ignore newlines until "baseurl:"
  The end-to-end genome assemblies of 12 representative strains from two closely related
  yeast species based on PacBio sequencing technology.
baseurl: "/Yeast_PacBio_2016" # the subpath of your site, e.g. /blog
url: "http://yjx1217.github.io" # the base hostname & protocol for your site
name: 'Jia-Xing Yue'
# email: your-email@domain.com
twitter_username: yjx1217
#github_username:  yjx1217

# Build settings
port: 4444
timezone:

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM

# Sass/SCSS
sass:
  sass_dir: _sass
include: ['_pages']

# theme
theme: minima